const languageOptions = [
    { text: 'English', callback_data: 'lang_en' },
    { text: 'Ukrainian', callback_data: 'lang_uk' },
    { text: 'Dutch', callback_data: 'lang_nl' },
    { text: 'French', callback_data: 'lang_fr' },
    { text: 'German', callback_data: 'lang_de' },
    { text: 'Spanish', callback_data: 'lang_es' },
    { text: 'Portuguese', callback_data: 'lang_pt' },
    { text: 'Italian', callback_data: 'lang_it' },
    { text: 'Russian', callback_data: 'lang_ru' },
    { text: 'Chinese', callback_data: 'lang_zh' },
    { text: 'Japanese', callback_data: 'lang_ja' },
    { text: 'Arabic', callback_data: 'lang_ar' },
    { text: 'Farsi', callback_data: 'lang_fa' },
    { text: 'Bengali', callback_data: 'lang_bn' },
    { text: 'Hindi', callback_data: 'lang_hi' },
    { text: 'Urdu', callback_data: 'lang_ur' },
    { text: 'Punjabi', callback_data: 'lang_pa' },
    { text: 'Vietnamese', callback_data: 'lang_vi' },
    { text: 'Yoruba', callback_data: 'lang_yo' },
    { text: 'Amazigh', callback_data: 'lang_amz' },
    { text: 'Romanian', callback_data: 'lang_ro' },
    { text: 'Bamileke', callback_data: 'lang_bam' },
    { text: 'Croatian', callback_data: 'lang_hr' }
];

const regions = {
    'lang_en': ['US', 'UK', 'Australia', 'Canada', 'Ireland', 'New Zealand', 'South Africa', 'Jamaica', 'Singapore', 'India'],
    'lang_uk': ['Kyiv', 'Lviv', 'Kharkiv', 'Odesa', 'Dnipro', 'Donetsk', 'Zaporizhzhia', 'Vinnytsia', 'Chernivtsi', 'Ivano-Frankivsk', 'Ternopil', 'Zakarpattia'],
    'lang_nl': ['Netherlands', 'Belgium', 'Suriname', 'Aruba', 'Curaçao', 'Sint Maarten'],
    'lang_fr': ['France', 'Canada', 'Belgium', 'Switzerland', 'Monaco', 'Luxembourg', 'Algeria', 'Morocco', 'Tunisia', 'Côte d\'Ivoire', 'Senegal', 'Haiti'],
    'lang_de': ['Germany', 'Austria', 'Switzerland', 'Liechtenstein', 'Luxembourg', 'Belgium'],
    'lang_es': ['Spain', 'Mexico', 'Argentina', 'Colombia', 'Peru', 'Venezuela', 'Chile', 'Ecuador', 'Guatemala', 'Cuba', 'Dominican Republic', 'Honduras', 'Paraguay', 'El Salvador', 'Nicaragua', 'Costa Rica', 'Puerto Rico', 'Uruguay', 'Panama', 'Equatorial Guinea'],
    'lang_pt': ['Portugal', 'Brazil', 'Angola', 'Mozambique', 'Cape Verde', 'Guinea-Bissau', 'São Tomé and Príncipe', 'East Timor', 'Equatorial Guinea', 'Macau'],
    'lang_it': ['Italy', 'Switzerland', 'San Marino', 'Vatican City', 'Slovenia', 'Croatia'],
    'lang_ru': ['Russia', 'Belarus', 'Kazakhstan', 'Kyrgyzstan', 'Tajikistan', 'Ukraine', 'Moldova', 'Latvia', 'Estonia', 'Lithuania'],
    'lang_zh': ['China', 'Taiwan', 'Singapore', 'Malaysia', 'Indonesia'],
    'lang_ja': ['Japan', 'Brazil', 'United States', 'Philippines'],
    'lang_ar': ['Egypt', 'Saudi Arabia', 'Morocco', 'Algeria', 'Sudan', 'Iraq', 'Syria', 'Tunisia', 'Jordan', 'Libya', 'Lebanon', 'Yemen', 'Oman', 'UAE', 'Kuwait', 'Qatar', 'Bahrain', 'Mauritania', 'Somalia', 'Djibouti', 'Comoros'],
    'lang_fa': ['Iran', 'Afghanistan', 'Tajikistan', 'Uzbekistan'],
    'lang_bn': ['Bangladesh', 'India', 'Saudi Arabia', 'UAE', 'UK', 'USA'],
    'lang_hi': ['India', 'Nepal', 'Fiji', 'UAE', 'USA', 'UK'],
    'lang_ur': ['Pakistan', 'India', 'UAE', 'UK', 'USA', 'Canada'],
    'lang_pa': ['India', 'Pakistan', 'UK', 'Canada', 'USA', 'Australia'],
    'lang_vi': ['Vietnam', 'USA', 'Australia', 'Canada', 'France', 'Germany'],
    'lang_yo': ['Nigeria', 'Benin', 'Togo', 'UK', 'USA'],
    'lang_amz': ['Morocco', 'Algeria', 'Libya', 'Tunisia', 'Mauritania', 'Mali', 'Niger', 'Burkina Faso'],
    'lang_ro': ['Romania', 'Moldova', 'Ukraine', 'Serbia', 'Hungary', 'Bulgaria'],
    'lang_bam': ['Cameroon', 'Nigeria'],
    'lang_hr': ['Croatia', 'Bosnia and Herzegovina', 'Serbia', 'Montenegro', 'Austria', 'Hungary', 'Italy']
};

const dialectMapping = {
    'US': 'en-US',
    'UK': 'en-GB',
    'Australia': 'en-AU',
    'Kyiv': 'uk-UA',
    'Chernihiv': 'uk-UA',
    'Zaporizhzhia': 'uk-UA',
    'Vinnytsia': 'uk-UA',
    'Chernivtsi': 'uk-UA',
    'Lviv': 'uk-UA',
    'Ivano-Frankivsk': 'uk-UA',
    'Hollandic': 'nl-NL',
    'Brabantic': 'nl-NL',
    'Limburgish': 'nl-NL',
    'Zeelandic': 'nl-NL',
    'West Flemish': 'nl-BE',
    'East Flemish': 'nl-BE',
    'Flemish': 'nl-BE',
    'Frisian': 'nl-NL',
    'Achterhoeks': 'nl-NL',
    'Low Saxon': 'nl-NL',
    'Utrecht Dialect': 'nl-NL',
    'Amelands': 'nl-NL',
    'Spain': 'es-ES',
    'Mexico': 'es-MX',
    'Argentina': 'es-AR',
    'Russia': 'ru-RU',
    'Ukraine': 'ru-UA',
    'Kazakhstan': 'ru-KZ',
    'China': 'zh-CN',
    'Taiwan': 'zh-TW',
    'Singapore': 'zh-SG',
    'France': 'fr-FR',
    'Canada': 'fr-CA',
    'Belgium': 'fr-BE',
    'Algeria': 'fr-DZ',
    'Japan': 'ja-JP',
    'Iran': 'fa-IR',
    'Afghanistan': 'fa-AF',
    'Tajikistan': 'fa-TJ',
    'Germany': 'de-DE',
    'Austria': 'de-AT',
    'Switzerland': 'de-CH',
    'Cameroon': 'bam-CM',
    'Algeria (Darija)': 'ar-DZ',
    'Morocco (Darija)': 'ar-MA',
    'Tunisia (Darija)': 'ar-TN',
    'Egyptian': 'ar-EG',
    'Levantine': 'ar-LE',
    'Portugal': 'pt-PT',
    'Brazil': 'pt-BR',
    'Italy': 'it-IT',
    'Switzerland': 'it-CH',
    'Bangladesh': 'bn-BD',
    'West Bengal': 'bn-IN',
    'Dhaka': 'bn-Dhaka',
    'Chittagong': 'bn-CTG',
    'Sylhet': 'bn-Sylhet',
    'Rangpur': 'bn-Rangpur',
    'Standard Hindi': 'hi-IN',
    'Bhojpuri': 'hi-IN',
    'Awadhi': 'hi-IN',
    'Braj': 'hi-IN',
    'Haryanvi': 'hi-IN',
    'Rajasthani': 'hi-IN',
    'Pakistan': 'ur-PK',
    'India': 'ur-IN',
    'Dakhini': 'ur-IN',
    'Rekhta': 'ur-IN',
    'Hyderabadi': 'ur-IN',
    'Eastern (India)': 'pa-IN',
    'Western (Pakistan)': 'pa-PK',
    'Majhi': 'pa-IN',
    'Doabi': 'pa-IN',
    'Malwai': 'pa-IN',
    'Pothwari': 'pa-IN',
    'Northern': 'vi-VN',
    'North-Central': 'vi-VN',
    'Central': 'vi-VN',
    'Southern': 'vi-VN',
    'Hue': 'vi-VN',
    'Hanoi': 'vi-Hanoi',
    'Saigon': 'vi-Saigon',
    'Standard Yoruba': 'yo-NG',
    'Oyo': 'yo-NG',
    'Ibadan': 'yo-NG',
    'Ijebu': 'yo-NG',
    'Ekiti': 'yo-NG',
    'Ife': 'yo-NG',
    'Ondo': 'yo-NG',
    'Owo': 'yo-NG',
    'Ijesa': 'yo-NG',
    'Tamazight': 'amz-MA',
    'Tashelhit': 'amz-MA',
    'Tarifit': 'amz-MA',
    'Kabyle': 'amz-DZ',
    'Chaoui': 'amz-DZ',
    'Tuareg': 'amz-DZ',
    'Zenaga': 'amz-MR',
    'Muntenian': 'ro-RO',
    'Moldavian': 'ro-MD',
    'Transylvanian': 'ro-RO',
    'Banat': 'ro-RO',
    'Aromanian': 'ro-RO',
    'Megleno-Romanian': 'ro-RO',
    'Istro-Romanian': 'ro-RO',
    'Croatia': 'hr-HR',
    'Bosnia and Herzegovina': 'hr-BA',
    'Serbia': 'hr-RS',
    'Montenegro': 'hr-ME'
};

const dialects = {
    'en-US': ['Boston', 'Chicago', 'Southern', 'Midwestern', 'Californian', 'New England', 'Appalachian', 'New York City', 'General American', 'African American Vernacular (AAVE)'],
    'en-GB': ['Brummie', 'Geordie', 'Cockney', 'Scouse', 'Yorkshire', 'Welsh English', 'West Country', 'Scottish English', 'Northern Irish', 'Received Pronunciation'],
    'en-AU': ['Torres Strait Creole', 'Broad Australian', 'Cultivated Australian', 'General Australian', 'Aboriginal English'],
    'en-CA': ['Quebec English', 'Maritime English', 'Canadian English', 'Newfoundland English'],
    'en-IE': ['Ulster English', 'Cork English', 'Dublin English', 'Hiberno-English'],
    'en-NZ': ['Māori English', 'New Zealand English'],
    'en-ZA': ['Cape Flats English', 'South African English', 'Black South African English'],
    'en-JM': ['Jamaican Patois', 'Jamaican English'],
    'en-SG': ['Singlish', 'Singaporean English'],
    'en-IN': ['Hinglish', 'Indian English'],
    'uk-UA': ['Boyko', 'Hutsul', 'Steppe', 'Sloboda', 'Lemko', 'Galician', 'Podillian', 'Polissian', 'Transcarpathian', 'Standard Ukrainian'],
    'nl-NL': ['Gronings', 'Veluws', 'Frisian', 'Limburgish', 'Hollandic', 'Low Saxon', 'Achterhoeks', 'Zeelandic', 'Brabantian', 'Standard Dutch'],
    'nl-BE': ['Antwerp', 'Flemish', 'Limburgish', 'Brabantian', 'West Flemish', 'East Flemish'],
    'fr-FR': ['Norman French', 'Parisian', 'Occitan', 'Breton French', 'Corsican French', 'Alsatian French', 'Standard French', 'Meridional'],
    'fr-CA': ['Quebec French', 'Acadian French', 'Métis French', 'Franco-Ontarian', 'Newfoundland French'],
    'de-DE': ['Hessian', 'Bavarian', 'Alemannic', 'Low German', 'Franconian', 'Upper Saxon', 'Thuringian', 'Standard German'],
    'de-AT': ['Carinthian', 'Tyrolean', 'Viennese German', 'Vorarlbergisch', 'Austrian Standard German'],
    'es-ES': ['Asturian', 'Galician', 'Murcian', 'Aragonese', 'Canarian', 'Andalusian', 'Extremaduran', 'Castilian'],
    'es-MX': ['Yucatec Spanish', 'Northern Mexican Spanish', 'Central Mexican Spanish', 'Mexican Spanish'],
    'pt-PT': ['Azorean Portuguese', 'Alentejo', 'Algarve', 'Madeiran Portuguese', 'European Portuguese'],
    'pt-BR': ['Carioca', 'Gaúcho', 'Paulistano', 'Amazofonia', 'Nordestino', 'Brazilian Portuguese'],
    'it-IT': ['Tuscan', 'Sicilian', 'Venetian', 'Romanesco', 'Piedmontese', 'Neapolitan', 'Sardinian', 'Standard Italian'],
    'ru-RU': ['Siberian', 'Far Eastern', 'Moscow dialect', 'Southern Russian', 'Northern Russian', 'Standard Russian', 'Saint Petersburg dialect'],
    'zh-CN': ['Min', 'Gan', 'Xiang', 'Hakka', 'Cantonese', 'Shanghainese', 'Sichuanese', 'Standard Mandarin'],
    'ja-JP': ['Okinawan', 'Tohoku-ben', 'Kansai-ben', 'Kyushu-ben', 'Hokkaido-ben', 'Shikoku-ben', 'Standard Japanese'],
    'ar-EG': ['Cairene', 'Bedouin', 'Sa\'idi Arabic', 'Alexandrian', 'Egyptian Arabic'],
    'ar-SA': ['Najdi Arabic', 'Bedouin', 'Gulf Arabic', 'Hejazi Arabic'],
    'fa-IR': ['Shirazi', 'Mashhadi', 'Tehrani', 'Isfahani', 'Western Persian'],
    'bn-BD': ['Noakhali', 'Sylheti', 'Rangpuri', 'Chittagonian', 'Standard Bengali'],
    'hi-IN': ['Bundeli', 'Awadhi', 'Bhojpuri', 'Haryanvi', 'Braj Bhasha', 'Standard Hindi'],
    'ur-PK': ['Sindhi Urdu', 'Punjabi Urdu', 'Karachi Urdu', 'Standard Urdu'],
    'pa-IN': ['Doabi', 'Majhi', 'Malwai', 'Powadhi', 'Puadhi'],
    'vi-VN': ['Hue dialect', 'Hanoi dialect', 'Saigon dialect', 'Northern Vietnamese', 'Central Vietnamese', 'Southern Vietnamese'],
    'yo-NG': ['Ijebu Yoruba', 'Ife Yoruba', 'Oyo Yoruba', 'Ekiti Yoruba', 'Ibadan Yoruba'],
    'amz-MA': ['Tarifit', 'Tashelhit', 'Tachelhit', 'Central Atlas Tamazight'],
    'ro-RO': ['Istro-Romanian', 'Aromanian', 'Moldavian', 'Daco-Romanian', 'Megleno-Romanian'],
    'bam-CM': ['Yemba', 'Medumba', 'Fe\'fe\'', 'Ghomala\'', 'Ngiemboon'],
    'hr-HR': ['Kajkavian', 'Dalmatian', 'Chakavian', 'Shtokavian', 'Istrian']
};


// Modify the exports to include the new function
module.exports = {
    languageOptions,
    regions,
    dialectMapping,
    dialects
};