const languageOptions = [
    { text: 'English', callback_data: 'lang_en' },
    { text: 'Ukrainian', callback_data: 'lang_uk' },
    { text: 'Dutch', callback_data: 'lang_nl' },
    { text: 'French', callback_data: 'lang_fr' },
    { text: 'German', callback_data: 'lang_de' },
    { text: 'Spanish', callback_data: 'lang_es' },
    { text: 'Portuguese', callback_data: 'lang_pt' },
    { text: 'Italian', callback_data: 'lang_it' },
    { text: 'Russian', callback_data: 'lang_ru' },
    { text: 'Chinese', callback_data: 'lang_zh' },
    { text: 'Japanese', callback_data: 'lang_ja' },
    { text: 'Arabic', callback_data: 'lang_ar' },
    { text: 'Farsi', callback_data: 'lang_fa' },
    { text: 'Bengali', callback_data: 'lang_bn' },
    { text: 'Hindi', callback_data: 'lang_hi' },
    { text: 'Urdu', callback_data: 'lang_ur' },
    { text: 'Punjabi', callback_data: 'lang_pa' },
    { text: 'Vietnamese', callback_data: 'lang_vi' },
    { text: 'Yoruba', callback_data: 'lang_yo' },
    { text: 'Amazigh', callback_data: 'lang_amz' },
    { text: 'Romanian', callback_data: 'lang_ro' },
    { text: 'Bamileke', callback_data: 'lang_bam' },
    { text: 'Croatian', callback_data: 'lang_hr' }
];

const regions = {
    'lang_en': ['US', 'UK', 'Australia'],
    'lang_uk': ['Kyiv', 'Chernihiv', 'Zaporizhzhia', 'Vinnytsia', 'Chernivtsi', 'Lviv', 'Ivano-Frankivsk'],
    'lang_nl': ['Hollandic', 'Brabantic', 'Limburgish', 'Zeelandic', 'West Flemish', 'East Flemish', 'Flemish', 'Frisian', 'Achterhoeks', 'Low Saxon', 'Utrecht Dialect', 'Amelands'],
    'lang_es': ['Spain', 'Mexico', 'Argentina'],
    'lang_ru': ['Russia', 'Ukraine', 'Kazakhstan'],
    'lang_zh': ['China', 'Taiwan', 'Singapore'],
    'lang_fr': ['France', 'Canada', 'Belgium', 'Algeria'],
    'lang_ja': ['Japan'],
    'lang_fa': ['Iran', 'Afghanistan', 'Tajikistan'],
    'lang_de': ['Germany', 'Austria', 'Switzerland'],
    'lang_bam': ['Cameroon'],
    'lang_ar': ['Algeria (Darija)', 'Morocco (Darija)', 'Tunisia (Darija)', 'Egyptian', 'Levantine'],
    'lang_pt': ['Portugal', 'Brazil'],
    'lang_it': ['Italy', 'Switzerland'],
    'lang_bn': ['Bangladesh', 'West Bengal', 'Dhaka', 'Chittagong', 'Sylhet', 'Rangpur'],
    'lang_hi': ['Standard Hindi', 'Bhojpuri', 'Awadhi', 'Braj', 'Haryanvi', 'Rajasthani'],
    'lang_ur': ['Pakistan', 'India', 'Dakhini', 'Rekhta', 'Hyderabadi'],
    'lang_pa': ['Eastern (India)', 'Western (Pakistan)', 'Majhi', 'Doabi', 'Malwai', 'Pothwari'],
    'lang_vi': ['Northern', 'North-Central', 'Central', 'Southern', 'Hue', 'Hanoi', 'Saigon'],
    'lang_yo': ['Standard Yoruba', 'Oyo', 'Ibadan', 'Ijebu', 'Ekiti', 'Ife', 'Ondo', 'Owo', 'Ijesa'],
    'lang_amz': ['Tamazight', 'Tashelhit', 'Tarifit', 'Kabyle', 'Chaoui', 'Tuareg', 'Zenaga'],
    'lang_ro': ['Muntenian', 'Moldavian', 'Transylvanian', 'Banat', 'Aromanian', 'Megleno-Romanian', 'Istro-Romanian'],
    'lang_hr': ['Croatia', 'Bosnia and Herzegovina', 'Serbia', 'Montenegro']
};

const dialectMapping = {
    'US': 'en-US',
    'UK': 'en-GB',
    'Australia': 'en-AU',
    'Kyiv': 'uk-UA',
    'Chernihiv': 'uk-UA',
    'Zaporizhzhia': 'uk-UA',
    'Vinnytsia': 'uk-UA',
    'Chernivtsi': 'uk-UA',
    'Lviv': 'uk-UA',
    'Ivano-Frankivsk': 'uk-UA',
    'Hollandic': 'nl-NL',
    'Brabantic': 'nl-NL',
    'Limburgish': 'nl-NL',
    'Zeelandic': 'nl-NL',
    'West Flemish': 'nl-BE',
    'East Flemish': 'nl-BE',
    'Flemish': 'nl-BE',
    'Frisian': 'nl-NL',
    'Achterhoeks': 'nl-NL',
    'Low Saxon': 'nl-NL',
    'Utrecht Dialect': 'nl-NL',
    'Amelands': 'nl-NL',
    'Spain': 'es-ES',
    'Mexico': 'es-MX',
    'Argentina': 'es-AR',
    'Russia': 'ru-RU',
    'Ukraine': 'ru-UA',
    'Kazakhstan': 'ru-KZ',
    'China': 'zh-CN',
    'Taiwan': 'zh-TW',
    'Singapore': 'zh-SG',
    'France': 'fr-FR',
    'Canada': 'fr-CA',
    'Belgium': 'fr-BE',
    'Algeria': 'fr-DZ',
    'Japan': 'ja-JP',
    'Iran': 'fa-IR',
    'Afghanistan': 'fa-AF',
    'Tajikistan': 'fa-TJ',
    'Germany': 'de-DE',
    'Austria': 'de-AT',
    'Switzerland': 'de-CH',
    'Cameroon': 'bam-CM',
    'Algeria (Darija)': 'ar-DZ',
    'Morocco (Darija)': 'ar-MA',
    'Tunisia (Darija)': 'ar-TN',
    'Egyptian': 'ar-EG',
    'Levantine': 'ar-LE',
    'Portugal': 'pt-PT',
    'Brazil': 'pt-BR',
    'Italy': 'it-IT',
    'Switzerland': 'it-CH',
    'Bangladesh': 'bn-BD',
    'West Bengal': 'bn-IN',
    'Dhaka': 'bn-Dhaka',
    'Chittagong': 'bn-CTG',
    'Sylhet': 'bn-Sylhet',
    'Rangpur': 'bn-Rangpur',
    'Standard Hindi': 'hi-IN',
    'Bhojpuri': 'hi-IN',
    'Awadhi': 'hi-IN',
    'Braj': 'hi-IN',
    'Haryanvi': 'hi-IN',
    'Rajasthani': 'hi-IN',
    'Pakistan': 'ur-PK',
    'India': 'ur-IN',
    'Dakhini': 'ur-IN',
    'Rekhta': 'ur-IN',
    'Hyderabadi': 'ur-IN',
    'Eastern (India)': 'pa-IN',
    'Western (Pakistan)': 'pa-PK',
    'Majhi': 'pa-IN',
    'Doabi': 'pa-IN',
    'Malwai': 'pa-IN',
    'Pothwari': 'pa-IN',
    'Northern': 'vi-VN',
    'North-Central': 'vi-VN',
    'Central': 'vi-VN',
    'Southern': 'vi-VN',
    'Hue': 'vi-VN',
    'Hanoi': 'vi-Hanoi',
    'Saigon': 'vi-Saigon',
    'Standard Yoruba': 'yo-NG',
    'Oyo': 'yo-NG',
    'Ibadan': 'yo-NG',
    'Ijebu': 'yo-NG',
    'Ekiti': 'yo-NG',
    'Ife': 'yo-NG',
    'Ondo': 'yo-NG',
    'Owo': 'yo-NG',
    'Ijesa': 'yo-NG',
    'Tamazight': 'amz-MA',
    'Tashelhit': 'amz-MA',
    'Tarifit': 'amz-MA',
    'Kabyle': 'amz-DZ',
    'Chaoui': 'amz-DZ',
    'Tuareg': 'amz-DZ',
    'Zenaga': 'amz-MR',
    'Muntenian': 'ro-RO',
    'Moldavian': 'ro-MD',
    'Transylvanian': 'ro-RO',
    'Banat': 'ro-RO',
    'Aromanian': 'ro-RO',
    'Megleno-Romanian': 'ro-RO',
    'Istro-Romanian': 'ro-RO',
    'Croatia': 'hr-HR',
    'Bosnia and Herzegovina': 'hr-BA',
    'Serbia': 'hr-RS',
    'Montenegro': 'hr-ME'
};

module.exports = {
    languageOptions,
    regions,
    dialectMapping
};